src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 */
class Artist
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $genre;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=Album::class, mappedBy="artist_id")
     */
    private $albums;

    public function __construct()
    {
        $this->albums = new ArrayCollection();
    }

    public function __toString(){
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Album[]
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->albums->contains($album)) {
            $this->albums[] = $album;
            $album->addArtistId($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->albums->removeElement($album)) {
            $album->removeArtistId($this);
        }

        return $this;
    }
}

src/Form/ArtistType.php
<?php

namespace App\Form;

use App\Entity\Artist;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',null,[
                'attr'=>[
                    'class'=>'form-control mb-3'
                ]
            ])
            ->add('genre',ChoiceType::class,[
                'attr'=>[
                    'class'=>'form-control'
                ],
                'choices' => 
                array
                (
                    'pop'=>'Pop',
                    'Dance / EDM (Electronic Dance Music)'=>'Dance / EDM (Electronic Dance Music)',
                    'Hip-hop and Rap'=>'Hip-hop and Rap',
                    'R&B'=>'R&B',
                    'Latin'=>'Latin',
                    'Rock'=>'Rock',
                    'Metal'=>'Metal',
                    'Country'=>'Country',
                    'Folk (also called Contemporary folk - wikipedia)'=>'Folk (also called Contemporary folk - wikipedia)',
                    'Classical'=>'Classical',
                    'Jazz'=>'Jazz',
                    'Blues'=>'Blues',
                    'Easy Listening'=>'Easy Listening',
                    'New Age'=>'New Age',
                    'World'=>'World / Traditional Folk',
                    'Eletronic'=>'Eletronic'
                ) 
            ])
            ->add('status',null,[
                'attr'=>[
                    'class'=>'ml-2 mt-3'
                ]
            ])
            ->add('created_at',HiddenType::class,[

            ])
            ->add('updated_at',HiddenType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Artist::class,
        ]);
    }
}

src/Controller/ArtistController.php
<?php

namespace App\Controller;

use App\Entity\Artist;
use App\Form\ArtistType;
use App\Helpers\Api\Artist as ApiArtist;
use App\Repository\ArtistRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/artist")
 */
class ArtistController extends AbstractController
{
    /**
     * @Route("/", name="artist_index", methods={"GET"})
     */
    public function index(ArtistRepository $artistRepository): Response
    {

        try{
            #$this->denyAccessUnlessGranted('ROLE_SUPERADMIN');
        }catch(\Exception $e){
        #    var_dump($e->getMessage());die;
        }
        

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        

        #var_dump($this->getUser()->getRoles());die;


        return $this->render('artist/index.html.twig', [
            'artists' => $artistRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="artist_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $artist = new Artist();
        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /**
             * TODO: Validate If artist is valid from API
             */

             /*
             if($this->isValidArtist($artist)){

             }*/
            
            $artist->setCreatedAt(new DateTime());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($artist);
            $entityManager->flush();

            return $this->redirectToRoute('artist_index');
        }

        return $this->render('artist/new.html.twig', [
            'artist' => $artist,
            'form' => $form->createView(),
        ]);
    }



    private function isValidArtist($artist):bool{

        $api = new ApiArtist();

        if($artist->getId()){
            $api->setArtistId($artist->getId());
        }

        /**
         * TODO: Check API Execution
         */
        $api->execute();

        return true;

    }

    /**
     * @Route("/{id}", name="artist_show", methods={"GET"})
     */
    public function show(Artist $artist): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('artist/show.html.twig', [
            'artist' => $artist,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="artist_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Artist $artist): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $form = $this->createForm(ArtistType::class, $artist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artist->setUpdatedAt(new DateTime());
            /**
             * TODO: Validate If artist is valid from API
             */

             /*
             if($this->isValidArtist($artist)){

             }*/
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('artist_index');
        }

        return $this->render('artist/edit.html.twig', [
            'artist' => $artist,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="artist_delete", methods={"POST"})
     */
    public function delete(Request $request, Artist $artist): Response
    {
        $is_admin = $this->isGranted('ROLE_ADMIN');

        if(!$is_admin){
            $this->addFlash('danger',"Only admins can delete albums");
            return $this->redirectToRoute('artist_index');
        }

        if ($this->isCsrfTokenValid('delete'.$artist->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($artist);
            $entityManager->flush();
        }

        return $this->redirectToRoute('artist_index');
    }
}

templates/artist/_delete_form.html.twig
<form method="post" action="{{ path('artist_delete', {'id': artist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artist.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/artist/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/artist/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Artist{% endblock %}

{% block body %}
    <h1>Edit Artist</h1>
    {{ include('artist/_form.html.twig', {'button_label': 'Update'}) }}

    <ul class="list list-inline">
        <li class="list-item-inline">
        
        </li>
        <li class="list-item-inline">
        <a href="{{ path('artist_index') }}" class="btn btn-primary">back to list</a>
        </li>
        <li class="list-item-inline">
        {{ include('artist/_delete_form.html.twig') }}
        </li>
    </ul>

    
{% endblock %}

templates/artist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist index{% endblock %}

{% block body %}
    <h1>Artist index</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Genre</th>
                <th>Status</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for artist in artists %}
            <tr>
                <td>{{ artist.id }}</td>
                <td>{{ artist.name }}</td>
                <td>{{ artist.genre }}</td>
                <td>{{ artist.status ? 'Yes' : 'No' }}</td>
                <td>{{ artist.createdAt ? artist.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ artist.updatedAt ? artist.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('artist_show', {'id': artist.id}) }}">show</a>
                    <a href="{{ path('artist_edit', {'id': artist.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('artist_new') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/artist/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Artist{% endblock %}

{% block body %}
    <h1>Create new Artist</h1>

    {{ include('artist/_form.html.twig') }}

    <a href="{{ path('artist_index') }}">back to list</a>
{% endblock %}

templates/artist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artist{% endblock %}

{% block body %}
    <h1>Artist</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ artist.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ artist.name }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{{ artist.genre }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ artist.status ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ artist.createdAt ? artist.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ artist.updatedAt ? artist.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('artist_index') }}">back to list</a>

    <a href="{{ path('artist_edit', {'id': artist.id}) }}">edit</a>

    {{ include('artist/_delete_form.html.twig') }}
{% endblock %}